test: &default
  PAYPAL_ENV: sandbox
  PAYPAL_CLIENT_ID:     YOUR_CREDENTIAL_HERE
  PAYPAL_CLIENT_SECRET:   YOUR_CREDENTIAL_HERE
  STRIPE_PUBLISHABLE_KEY: YOUR_CREDENTIAL_HERE
  STRIPE_SECRET_KEY:  YOUR_CREDENTIAL_HERE
development:
  <<: *default